language: node_js
node_js:
  - 6
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master